dist: trusty
sudo: required
language: node_js
node_js:
  - node
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
env:
  global:
    - DB_HOST=127.0.0.1
    - DB_DATABASE=test
    - DB_USER=root
